[profile.release]
lto = true
opt-level = "s"
panic = "abort"

[workspace]
members = [
    "provider",
    "target/provider-caller-utils",
    "target/provider-caller-util?",
    "target/provider-caller-util?",
]
resolver = "2"
